apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: us-central1-docker.pkg.dev/webapp-pipeline-project/app-repo/hello-node-app:latest
        ports:
        - containerPort: 3000
